### ISSUE TITLE
Throwing exceptions

### ISSUE THREAD

**Issue by mariorbarbbosa** [evert/slowdeath#1]
Exception in thread Thread-32:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "slowdeath.py", line 63, in run
    s.send('abc=123&')
error: [Errno 32] Broken pipe

**Comment by evert** [comment]
It's been over 5 years since I wrote and used this tool. I'm no longer interested in developing it, and also not sure what would cause this bug. Perhaps it's better to find an alternative!
